bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh1_kmeans.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh2_kmeans.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm1_kmeans.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm2_kmeans.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh1_linear.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh2_linear.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm1_linear.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm2_linear.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh1_pca.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh2_pca.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm1_pca.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm2_pca.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh1_random.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh2_random.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm1_random.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm2_random.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh1_similarity.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh2_similarity.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm1_similarity.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm2_similarity.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh1_text.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTh2_text.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm1_text.sh
bash ./scripts/LLM4Time/Ablation_pmethod/LLM4Time_ETTm2_text.sh